In [3]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(arr*3)

[10 20 30 40 50]
[ 30  60  90 120 150]


In [5]:
arr1=np.min([1,2,3,4,5])
arr2=np.max([12,13,14,15,16])
arr3=np.average([20,10,3,24,5])
arr4=np.vstack([12,10,20,30,3])
arr5=np.hstack([12,2,34,56,1])
arr6=np.sum([23,13,42,15,2])
arr7=np.sort([23,13,15,26,76])
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(arr7)

1
16
12.4
[[12]
 [10]
 [20]
 [30]
 [ 3]]
[12  2 34 56  1]
95
[13 15 23 26 76]


In [20]:
arr=np.array([12,45,34,56,70])
result = np.where(arr==34)
print(result)

(array([2]),)
